{
	"version": 1674426448,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/soruspt-sheet0.png",
		"images/soruspt-sheet1.png",
		"images/seceneka-sheet0.png",
		"images/seceneka-sheet1.png",
		"images/secenekb-sheet0.png",
		"images/secenekb-sheet1.png",
		"images/secenekb-sheet2.png",
		"images/bilgispt-sheet0.png",
		"images/sonucspt-sheet0.png",
		"images/arkaplan-sheet0.png",
		"images/devamspt-sheet0.png",
		"images/tiledbackground.png",
		"images/ilerig-sheet0.png",
		"images/tiledbackground2.png",
		"images/sonucespt-sheet0.png",
		"images/sprite-sheet0.png",
		"images/anasayfa-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/dogruses (online-audio-converter.com).m4a",
		"media/dogruses (online-audio-converter.com).ogg",
		"media/yanlisses (online-audio-converter.com).m4a",
		"media/yanlisses (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"sorular.txt"
	]
}